import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <aside className={styles.sidemenu}>
          <div className={styles.side_menu_button}>
            <span>+</span> New Chat</div>
         </aside>
         <section className={styles.chatbot}>
         <div className={styles.chat_log}>
          <div className={styles.chat_message}>
            <div className={styles.chat_message_center}>
              <div className={styles.avatar}></div>
              <div className={styles.message}>Test Message</div>
            </div>
          </div>
          <div className={`${styles.chat_message} ${styles.chat_message_ai}`}>
            <div className={styles.chat_message_center}>
              <div className={`${styles.avatar} ${styles.avatar_ai}`}></div>
              <p className={styles.message}>This throws an error because it thinks I'm subtracting the variables pd and text from styles.projects in the first interpolation and the variables pd and subdetail from styles.proejcts in the second interpolation. Jacob Smit's comment above works though</p>
            </div>
          </div>
         </div>
            <div className={styles.chat_input}>
              <textarea rows={1} className={styles.chat_input_area} placeholder="Type your message"></textarea>
            </div>
         </section>
      </main>
    </>
  )
}
