import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <aside className={styles.sidemenu}>
          <div className={styles.side_menu_button}>
            <span>+</span> New Chat</div>
         </aside>
         <section className={styles.chatbot}>
            <div className={styles.chat_input}>
              <textarea rows={1} className={styles.chat_input_area} placeholder="Type your message"></textarea>
            </div>
         </section>
      </main>
    </>
  )
}
